### ISSUE TITLE
Stacktrace when trying to run "inv install"

### ISSUE THREAD

**Issue by Max-Leopold** [nyash-qq/galaxy-plugin-twitch#19]
When I try to install the plugin I get the following Stacktrace:
```

Traceback (most recent call last):
  File "c:\users\mir\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mir\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mir\AppData\Local\Programs\Python\Python37-32\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "c:\users\mir\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\mir\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 182, in _prepareconfig
    config = get_config()
  File "c:\users\mir\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 156, in get_config
    pluginmanager.import_plugin(spec)
  File "c:\users\mir\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 530, in import_plugin
    __import__(importspec)
  File "c:\users\mir\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\tmpdir.py", line 25, in <module>
    class TempPathFactory(object):
  File "c:\users\mir\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\tmpdir.py", line 35, in TempPathFactory
    lambda p: Path(os.path.abspath(six.text_type(p)))
TypeError: attrib() got an unexpected keyword argument 'convert'
```

Don't know if you are aware of this error.

Environment:
- Windows 10
- Python 3.7.4

**Comment by Rall3n** [comment]
The stack trace you provided does not imply that the fault lies with this package. Are you executing the command `inv install` inside the project root (`./galaxy-plugin-twitch`)?
